FROM node:20.11

WORKDIR /app

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get -y install default-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm init -y && npm install allure-commandline

CMD ["npx", "allure", "generate", "--clean"]
# CMD ["bash"]
